# Generated by Django 5.0.3 on 2026-01-13 07:50

import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-created_at',), 'verbose_name': '系统日志', 'verbose_name_plural': '系统日志'},
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='log_log_level_29c09a_idx',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='log_log_categor_9b3293_idx',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='log_log_user_id_d7cd88_idx',
        ),
        migrations.RemoveField(
            model_name='log',
            name='created',
        ),
        migrations.RemoveField(
            model_name='log',
            name='modified',
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='log',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['level', 'created_at'], name='log_log_level_5a57b9_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['category', 'created_at'], name='log_log_categor_58452d_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'created_at'], name='log_log_user_id_8bb951_idx'),
        ),
    ]
