# Generated by Django 5.0.3 on 2025-11-15 20:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], default='INFO', help_text='日志的严重程度', max_length=10, verbose_name='日志级别')),
                ('category', models.CharField(choices=[('auth', '认证'), ('user', '用户'), ('system', '系统'), ('api', 'API'), ('admin', '管理'), ('notification', '通知'), ('other', '其他')], default='system', help_text='日志所属的功能模块', max_length=20, verbose_name='日志类别')),
                ('action', models.CharField(help_text='执行的具体操作，如登录、创建、删除等', max_length=100, verbose_name='操作动作')),
                ('message', models.TextField(help_text='详细的日志描述信息', verbose_name='日志消息')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='操作来源的IP地址', null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, help_text='浏览器或客户端信息', verbose_name='用户代理')),
                ('path', models.CharField(blank=True, help_text='请求的URL路径', max_length=255, verbose_name='请求路径')),
                ('method', models.CharField(blank=True, help_text='HTTP请求方法，如GET、POST等', max_length=10, verbose_name='请求方法')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP响应状态码', null=True, verbose_name='状态码')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='额外的结构化数据，如请求参数、响应数据等', verbose_name='额外数据')),
                ('user', models.ForeignKey(blank=True, help_text='执行操作的用户，可为空表示系统操作', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['level', 'created'], name='log_log_level_29c09a_idx'), models.Index(fields=['category', 'created'], name='log_log_categor_9b3293_idx'), models.Index(fields=['user', 'created'], name='log_log_user_id_d7cd88_idx')],
            },
        ),
    ]
