# Generated by Django 5.1.6 on 2025-12-15 10:18

import uuid
import apps.user.model
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=50, unique=True, verbose_name="角色标识")),
                ("name", models.CharField(max_length=100, verbose_name="角色名称")),
                ("description", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_system", models.BooleanField(default=False, verbose_name="是否系统预置")),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "具有该用户名的用户已存在。"},
                        help_text="必填。150 个字符或更少，仅包含字母、数字和@/./+/-/_。",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="用户名",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="邮箱地址")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "ordering": ("-created_at",),
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="电话号码")),
                ("nickname", models.CharField(blank=True, max_length=50, null=True, verbose_name="昵称")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "男"),
                            ("female", "女"),
                            ("other", "其他"),
                            ("prefer_not_to_say", "不愿透露"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="出生日期")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to=apps.user.model.user_avatar_path, verbose_name="头像")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("inactive", "不活跃"), ("suspended", "被暂停")],
                        default="active",
                        max_length=20,
                        verbose_name="账户状态",
                    ),
                ),
                ("login_count", models.IntegerField(default=0, verbose_name="登录次数")),
                ("last_activity", models.DateTimeField(default=django.utils.timezone.now, verbose_name="最后活动时间")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("register", "注册"),
                            ("profile_update", "资料更新"),
                            ("password_change", "修改密码"),
                            ("avatar_upload", "上传头像"),
                            ("admin_action", "管理操作"),
                        ],
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="活动描述")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP地址")),
                ("user_agent", models.TextField(blank=True, null=True, verbose_name="用户代理")),
                ("metadata", models.JSONField(blank=True, null=True, verbose_name="元数据")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户活动",
                "verbose_name_plural": "用户活动",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentUpload",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/", verbose_name="文件")),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名称")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("avatar", "头像"), ("document", "文档"), ("image", "图片"), ("other", "其他")],
                        default="other",
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                ("file_size", models.IntegerField(default=0, verbose_name="文件大小（字节）")),
                ("content_type", models.CharField(default="application/octet-stream", max_length=100, verbose_name="内容类型")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("approved", "已批准"), ("rejected", "已拒绝")],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True, verbose_name="审核备注")),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档上传",
                "verbose_name_plural": "文档上传",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="user.role",
                        verbose_name="角色",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色",
                "verbose_name_plural": "用户角色",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(fields=("user", "role"), name="unique_user_role"),
        ),
    ]
