# Generated by Django 5.0.3 on 2025-11-19 14:52

import uuid
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SettingCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("system", "系统配置"),
                            ("feature", "功能开关"),
                            ("ui", "界面配置"),
                            ("email", "邮件配置"),
                            ("security", "安全配置"),
                            ("notification", "通知配置"),
                            ("api", "API配置"),
                            ("business", "业务配置"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="分类名称",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="分类描述")),
                ("icon", models.CharField(blank=True, help_text="Bootstrap图标类名，如：bi-gear", max_length=50, null=True, verbose_name="图标")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "设置分类",
                "verbose_name_plural": "设置分类",
                "ordering": ("sort_order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "key",
                    models.CharField(
                        help_text="设置的唯一标识符，使用点分命名法，如：system.site_name",
                        max_length=100,
                        unique=True,
                        verbose_name="设置键名",
                    ),
                ),
                ("name", models.CharField(help_text="设置的显示名称", max_length=200, verbose_name="设置名称")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("boolean", "布尔值"),
                            ("integer", "整数"),
                            ("float", "浮点数"),
                            ("string", "字符串"),
                            ("text", "长文本"),
                            ("json", "JSON数据"),
                            ("url", "URL地址"),
                            ("email", "邮箱地址"),
                        ],
                        default="string",
                        help_text="设置值的数据类型",
                        max_length=20,
                        verbose_name="值类型",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "系统配置"),
                            ("feature", "功能开关"),
                            ("ui", "界面配置"),
                            ("email", "邮件配置"),
                            ("security", "安全配置"),
                            ("notification", "通知配置"),
                            ("api", "API配置"),
                            ("business", "业务配置"),
                        ],
                        default="system",
                        help_text="设置的分类",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                ("value", models.TextField(blank=True, help_text="设置的实际值", null=True, verbose_name="设置值")),
                ("default_value", models.TextField(blank=True, help_text="设置的默认值", null=True, verbose_name="默认值")),
                ("description", models.TextField(blank=True, help_text="设置的详细说明", null=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, help_text="是否启用此设置项", verbose_name="是否启用")),
                ("is_editable", models.BooleanField(default=True, help_text="是否允许通过界面编辑", verbose_name="是否可编辑")),
                ("sort_order", models.IntegerField(default=0, help_text="设置项在界面中的显示顺序，数值越小越靠前", verbose_name="排序")),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='设置的验证规则，如：{"min": 0, "max": 100, "required": true}',
                        verbose_name="验证规则",
                    ),
                ),
                (
                    "extra_options",
                    models.JSONField(blank=True, default=dict, help_text="设置的额外选项，用于前端界面渲染", verbose_name="额外选项"),
                ),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
                "ordering": ("-created_at",),
            },
        ),
    ]
