"""
Django settings for system project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z_09u&if(5slx8q%zab4+a+q^r+#mq*ib6o&4#=s0f*lib*xj-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# 禁用自动添加斜杠，避免与 Django Ninja API 路由冲突
APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 第三方应用
    'corsheaders',
    'ninja',  # Django Ninja
    'ninja_extra',  # Django Ninja Extra
    
    # 认证和权限
    'allauth',  # Django Allauth
    'allauth.account',  # 账户管理
    'allauth.socialaccount',  # 社交登录
    'model_utils',  # Django Model Utils - 模型工具
    'captcha',  # Django Simple Captcha - 验证码
    
    # 自定义应用
    'apps.user.apps.UserConfig',  # User微服务应用
    'apps.web',   # Web视图应用
    'apps.notification',  # Notification微服务应用
    'apps.log',  # Log日志应用
    'apps.setting',  # 设置管理应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Allauth 中间件
    'apps.core.middleware.log_middleware.LogMiddleware',  # 日志记录中间件
]

ROOT_URLCONF = 'system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'system.wsgi.application'
ASGI_APPLICATION = 'system.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 自定义用户模型
AUTH_USER_MODEL = 'user.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS设置
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Ninja API设置
NINJA_PAGINATION_PER_PAGE = 20
NINJA_PAGINATION_MAX_PER_PAGE = 100

# ==================
# Django Allauth 设置
# ==================
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth 后端
    'guardian.backends.ObjectPermissionBackend',  # Guardian 后端
)

# Allauth 设置
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # 支持用户名或邮箱登录
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # 邮箱验证方式：'none', 'optional', 'mandatory'
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True  # 注册时要求输入两次密码
ACCOUNT_SESSION_REMEMBER = True  # 记住登录状态
ACCOUNT_LOGOUT_REDIRECT_URL = '/login/'  # 登出后重定向
LOGIN_URL = '/login/'  # 未登录用户访问受保护页面时重定向到登录页
LOGIN_REDIRECT_URL = '/user/home/'  # 登录后重定向

# 邮箱设置
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 开发环境下使用控制台输出邮件

# ==================
# Django Guardian 设置
# ==================
# 对象级权限 - 在AUTHENTICATION_BACKENDS中已配置

# ==================
# Django Model Utils 设置
# ==================
# 模型工具默认设置
MODEL_UTILS_USE_TZ = True

# ==================
# Django Simple Captcha 设置
# ==================
# 验证码配置
CAPTCHA_OUTPUT_FORMAT = 'image'
CAPTCHA_IMAGE_SIZE = (120, 40)  # 验证码图片大小
CAPTCHA_BACKGROUND_COLOR = '#ffffff'  # 背景色
CAPTCHA_FOREGROUND_COLOR = '#000000'  # 前景色（文字颜色）
CAPTCHA_FONT_SIZE = 22  # 字体大小
CAPTCHA_LENGTH = 4  # 验证码长度
CAPTCHA_TIMEOUT = 5  # 验证码过期时间（分钟）
CAPTCHA_DICT = {}  # 自定义验证字符集
CAPTCHA_PERSISTENT_KEY = 'captcha_persistent'
CAPTCHA_TEST_MODE = False  # 生产环境设为True可跳过验证码

# 验证码路由前缀
CAPTCHA_URL_PREFIX = 'captcha/'

# ==================
# X-Frame-Options 设置
# ==================
# 允许同源iframe嵌入（用于API文档页面）
X_FRAME_OPTIONS = 'SAMEORIGIN'
