# Generated by Django 5.0.3 on 2026-01-14 10:21

import django.utils.timezone
import uuid
from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_metadata_notification_sent_role'),
    ]

    operations = [
        # 直接重建通知表以对齐 BaseModel 的 UUID 主键与软删字段
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('category', models.CharField(max_length=30, verbose_name='类别')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败')], default='pending', max_length=10, verbose_name='状态')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='计划发送时间')),
                ('sent_role', models.CharField(blank=True, help_text='按角色发送时的角色标识（all/管理员/用户）', max_length=20, null=True, verbose_name='发送角色')),
                ('recipient', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ('-created_at',),
            },
        ),
    ]
