# Generated by Django 5.0.3 on 2025-12-15 10:18

import app.user.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file_type', models.CharField(choices=[('avatar', 'avatar'), ('头像', '头像'), ('document', 'document'), ('文档', '文档'), ('image', 'image'), ('图片', '图片'), ('other', 'other'), ('其他', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小（字节）')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100, verbose_name='内容类型')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('待处理', '待处理'), ('approved', 'approved'), ('已批准', '已批准'), ('rejected', 'rejected'), ('已拒绝', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '文档上传',
                'verbose_name_plural': '文档上传',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('activity_type', models.CharField(choices=[('login', 'login'), ('登录', '登录'), ('logout', 'logout'), ('登出', '登出'), ('register', 'register'), ('注册', '注册'), ('profile_update', 'profile_update'), ('资料更新', '资料更新'), ('password_change', 'password_change'), ('修改密码', '修改密码'), ('avatar_upload', 'avatar_upload'), ('上传头像', '上传头像'), ('admin_action', 'admin_action'), ('管理操作', '管理操作')], max_length=20, verbose_name='活动类型')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='元数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('prefer_not_to_say', '不愿透露')], max_length=20, null=True, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=app.user.models.user_avatar_path, verbose_name='头像')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('suspended', '被暂停')], default='active', max_length=20, verbose_name='账户状态')),
                ('login_count', models.IntegerField(default=0, verbose_name='登录次数')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最后活动时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
