# Generated by Django 5.0.3 on 2025-11-08 13:50

import app.user.model
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='file_type',
            field=models.CharField(choices=[('avatar', 'avatar'), ('头像', '头像'), ('document', 'document'), ('文档', '文档'), ('image', 'image'), ('图片', '图片'), ('other', 'other'), ('其他', '其他')], default='other', max_length=20, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('待处理', '待处理'), ('approved', 'approved'), ('已批准', '已批准'), ('rejected', 'rejected'), ('已拒绝', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'login'), ('登录', '登录'), ('logout', 'logout'), ('登出', '登出'), ('register', 'register'), ('注册', '注册'), ('profile_update', 'profile_update'), ('资料更新', '资料更新'), ('password_change', 'password_change'), ('修改密码', '修改密码'), ('avatar_upload', 'avatar_upload'), ('上传头像', '上传头像'), ('admin_action', 'admin_action'), ('管理操作', '管理操作')], max_length=20, verbose_name='活动类型'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission_type',
            field=models.CharField(choices=[('user_management', 'user_management'), ('用户管理', '用户管理'), ('content_moderation', 'content_moderation'), ('内容管理', '内容管理'), ('system_admin', 'system_admin'), ('系统管理', '系统管理'), ('api_access', 'api_access'), ('API访问', 'API访问'), ('data_export', 'data_export'), ('数据导出', '数据导出'), ('bulk_operations', 'bulk_operations'), ('批量操作', '批量操作')], max_length=30, verbose_name='权限类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=app.user.model.user_avatar_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
