# Generated by Django 5.0.3 on 2025-11-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_bio_remove_userprofile_location_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # 不执行数据库操作（表可能不存在）
            state_operations=[
                migrations.DeleteModel(
                    name='UserPermission',
                ),
            ]
        ),
    ]
