# Generated by Django 5.0.3 on 2025-11-09 09:49

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='user_role_permission_unique',
        ),
        migrations.AlterField(
            model_name='role',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission_type',
            field=models.CharField(choices=[('user_management', 'user_management'), ('用户管理', '用户管理'), ('content_moderation', 'content_moderation'), ('内容管理', '内容管理'), ('system_admin', 'system_admin'), ('系统管理', '系统管理'), ('api_access', 'api_access'), ('API访问', 'API访问'), ('data_export', 'data_export'), ('数据导出', '数据导出'), ('bulk_operations', 'bulk_operations'), ('批量操作', '批量操作')], max_length=30, verbose_name='权限类型'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission_type')},
        ),
    ]
