# Generated by Django 5.0.3 on 2025-11-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_0004_delete_userpermission_0005_remove_rolepermission'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # 不执行数据库操作（表可能不存在）
            state_operations=[
                migrations.RemoveField(
                    model_name='userprofile',
                    name='roles',
                ),
                migrations.RemoveField(
                    model_name='rolepermission',
                    name='role',
                ),
                migrations.AlterUniqueTogether(
                    name='rolepermission',
                    unique_together=None,
                ),
                migrations.DeleteModel(
                    name='Role',
                ),
                migrations.DeleteModel(
                    name='RolePermission',
                ),
            ]
        ),
    ]
