# Generated by Django 5.0.3 on 2025-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_role',
            field=models.CharField(blank=True, help_text='按角色发送时的角色标识（all/管理员/用户）', max_length=20, null=True, verbose_name='发送角色'),
        ),
    ]
